### ISSUE TITLE
High Level Component `SideBar`

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#108]
### Description

Create a high-level SideBar component that will be used across multiple pages of the application. This component should be designed to be flexible, reusable, and easy to integrate into various parts of the application.

### Suggested Solution

**Structure:**
- A container that holds the entire sidebar.
- Menu items that can be dynamically rendered based on the provided data.
- Optionally, submenus for certain menu items.
- A footer section for additional links or information.

**Functionality:**
- Collapsible sections for menu items with submenus.
- Highlight the active menu item based on the current route.
- Optional icons for each menu item.
- Accessibility features like keyboard navigation...

**Styling:**
- Should be responsive and adapt to different screen sizes.
- Follow the application's design system for colors, fonts, and spacing.
- Smooth animations for expanding/collapsing sections.

### Additional Context

This `SideBar` component will be a critical part of the user interface, as it will provide navigation across different sections of the application.

**Comment by mad-moo** [comment]
I'm closing all issues on new high-level components. The ideas in the current issues are quite out of date and don't fit the current state of Rio. IMO we should have another discussion on which components we want to add, and add appropriate new issues.
