### ISSUE TITLE
`SeparatorListItem` doesn't allocate any size in `ListView`

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#109]
### Describe the bug

When using `SeparatorListItem` in a `ListView` it doesn't get any height allocated.

### Screenshots/Videos

**How it looks:**
<img width="462" alt="image" src="https://github.com/user-attachments/assets/e274bea7-3dea-4a21-86ec-48c81f9dc43b">

**How it should look:**
<img width="519" alt="image" src="https://github.com/user-attachments/assets/f21bd81a-9128-44aa-a4b5-a46c076edca0">

### Operating System

MacOS

### What browsers are you seeing the problem on?

Chrome, Safari

### What device are you using?

Desktop

**Comment by mad-moo** [comment]
Fixed in cc48401105ae48751a144347d924d02fccfccee4
