### ISSUE TITLE
Unintended onHover Event on Minor Style `Buttons` and `IconButtons` if `is_sensitive=False`

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#113]
### Describe the bug

`Button's` and `IconButton's` with `style=minor` and `is_sensitive=False` currently trigger an onhover event. This behavior is not expected and should be removed.

### Example to reproduce:
```python
class BugExample(rio.Component):

    def build(self):
        return rio.Column(
            rio.Button(
                "minor",
                style="minor",
                is_sensitive=False,
            ),
            rio.Spacer(height=5),
            rio.IconButton(
                icon="material/castle",
                style="minor",
                is_sensitive=False,
            ),
            align_y=0.5,
            align_x=0.5,
            width=20,
        )
```

### Steps to Reproduce

1. Create a `Button` or `IconButton` with `style=minor` and `is_sensitive=False`.
2. Hover over the `Button` or `IconButton`.

### Screenshots/Videos

**Button:**

https://github.com/user-attachments/assets/b20105cb-1b5b-4973-9af5-8b6053748630

**IconButton:**

https://github.com/user-attachments/assets/fb7fa84d-1249-49eb-900a-bcdc5477556c

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome, Edge

**Comment by mad-moo** [comment]
Fixed in 2c5a3774dde39f80955bbaf6b40fb9140206fb06
