### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#12]

**Comment by shubham-kshetre** [comment]
Hello @Sn3llius, I can start contributing with this issue

**Comment by Sn3llius** [comment]
@shubham-kshetre Unfortunately, I've already completed my draft. We're currently discussing some points internally, and it's set to be released this weekend. 

I have three topics where I'd really appreciate a draft. I'll be opening issues for the following:
- Code of Conduct
- Security Policy
- Issue Templates

maybe something interesting for you?

**Comment by shubham-kshetre** [comment]
Okay, I can start with Issue Templates. Feel free to open an issue for it and provide any details on the specific format or content you'd like to include. Also, I'm excited to use my DevOps skills

**Comment by Sn3llius** [comment]
@shubham-kshetre i've opened some issues yesterday. Feel free to contribute!

if you have any questions join our discord server and ask me there. ;)
