### ISSUE TITLE
Support FastAPI Routes Without Explicit Index Specification

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#122]
Currently, FastAPI routes require explicitly specifying an index. This can be cumbersome and error-prone, especially for larger applications with many routes. It would be beneficial to have a mechanism that allows FastAPI routes to be defined without the need to specify an explicit index, making route definitions cleaner and more intuitive.

### Possible Solution:
Implement an internal mechanism in FastAPI that automatically manages route indexing, ensuring routes are registered in the order they are added.

**Comment by mad-moo** [comment]
@Aran-Fey I remember you working on something like this. Is this issue a thing of the past?
