### ISSUE TITLE
Overlays May Take Up Space in the Parent

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#124]
There is an issue where overlays take up space in their parents. This behavior can lead to misaligned layouts. Overlays should be positioned in a way that does not affect the layout or dimensions of their parent container.

**Comment by mad-moo** [comment]
This is particularly noticeable when added to Rows/Columns with spacing set. The spacing will appear once before, and once after the Overlay.

**Comment by mad-moo** [comment]
I don't see a practical way to fix this given the switch to layout using CSS. Changing this would require drastic changes to how widgets are implemented on the client, and ugly code to circumvent CSS. I'll close this as it's neither terribly important, nor practical to change.
