### ISSUE TITLE
[BUG]: Missing dependencies for crypto-dashboard

### ISSUE THREAD

**Issue by Sylphe88** [rio-labs/rio#126]
### Describe the bug

Creating a RIO project from the crypto-dashboard template does not include required dependencies:
- plotly
- pandas
- pycoingecko

Resulting in a failing rio run (not quite failing, because the wsgi still starts!)

I haven't looked into the way RIO projects are instantiated, but it could make sense to attach a dependency file (of any form, from requirements.txt to pyprojects.toml or setup.py) so dependencies are automatically installed.

Other than that, thumbs up on this project!

### Steps to Reproduce

Run `rio new --template crypto-dashboard` from a fresh venv.
Run `rio run`, which should ouput ModuleNotFound error

### Operating System

Windows

### What browsers are you seeing the problem on?

Other

### What device are you using?

Desktop

**Comment by Sn3llius** [comment]
Hey there is a `requirements.txt` file in your repo. 

Run `rio new --template crypto-dashboard`
Run `cd YOUR_PROJECT`
Run `pip install -r requirements.txt`
Run `rio run`

If pip isn't installed, run `python -m ensurepip`. I hope this helps. I'll add the necessary steps to our examples, but you can also find the required steps in your terminal.
