### ISSUE TITLE
Update Examples to `min_width` / `min_height`

### ISSUE THREAD

**Issue by mad-moo** [rio-labs/rio#128]
Recent updates have replaced the `width` and `height` parameters with `min_width`, `grow_x`, and others. A lot of code in Rio itself still uses the old-style parameters though, thus leading to deprecation warnings, and general confusion.

Search for & replace all outdated usages.

**Comment by Sn3llius** [comment]
It seems like most of it is already completed, right?

**Comment by mad-moo** [comment]
Yeah, I went through the entire codebase and replaced everything I could find. I'm mostly worried now about the examples found in the documentation of all components.

In general, with all the changes that happened as of late I think the entire framework needs some thorough testing

**Comment by mad-moo** [comment]
@Sn3llius this is safe to close, correct?
