### ISSUE TITLE
[Feature Request] Local Filesystem Interaction Examples

### ISSUE THREAD

**Issue by non-npc** [rio-labs/rio#130]
### Description

Any examples highlighting using the local file system for file operations?
I am trying to create a simple file browser like windows file explorer but consistently run into cross-origin errors in the webview.

### Suggested Solution

an example displaying how to interact with the local file system without cross-origin errors in the webview

**Comment by mad-moo** [comment]
Hey! Can you give a few more details about what you're doing exactly? Since file system access is handled by Python and not Rio I'm not sure what to include in the example. A minimum runnable example would be great so we can reproduce the CORS errors.

**Comment by Sn3llius** [comment]
@non-npc can you provide please a minimum runnable example so we can reproduce the CORS errors? Thank you!
