### ISSUE TITLE
Drawers Cut Off their Content

### ISSUE THREAD

**Issue by mad-moo** [rio-labs/rio#149]
### Describe the bug

The size of a drawer always follows its anchor. This is usually fine, but sometimes the content of the drawer is actually the larger of the two. In that case the content is unceremoniously truncated.

### Steps to Reproduce

- Create a `rio.Drawer`
  - Use `rio.Text` (or anything small) as anchor
  - Fill the content with any components until they exceed the screen size.

**Comment by Aran-Fey** [comment]
Drawers are now always large enough to contain both their anchor and their content.
