### ISSUE TITLE
[BUG]: Incorrect MIME type while serving JS scripts

### ISSUE THREAD

**Issue by dunivlorraine** [rio-labs/rio#151]
### Describe the bug

When running the app, JS scripts are served with the incorrect MIME type `text/plain` instead of `application/javascript`. This causes the script to be blocked by the browser with the following message in the console:

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

### Steps to Reproduce

For my setup, I installed Rio via Poetry. Just run the command `poetry run rio run`, then go to `localhost://8000`. The app will not load. Open your console and see the message and that the MIME type of the script is indeed `text/plain`:

![image](https://github.com/user-attachments/assets/2f465eba-c5bf-45da-ad9b-3e21a5cad25d)

You can actually bypass this error by manually changing the MIME type of the JS index script:

![image](https://github.com/user-attachments/assets/ce36a105-e287-4e0d-a13c-d0364d9c8a91)

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome, Firefox

### Browser version

Latest

### What device are you using?

Desktop

### Additional context

This may not be directly an issue from Rio, it may be from Fastapi.

**Comment by mad-moo** [comment]
Hey

Thank you for reporting this. I've seen a similar report in the past, but every time I tried to reproduce it the files were served using the correct MIME types. So a couple more questions:

- Which Rio version are you on?
- Can you try to make the HTTP request using another tool (like curl) and see which MIME types you get
- Are there any other tools running that might be intercepting HTTP requests. For example, are you on a corporate network that is verifying all traffic

We'll try to reproduce this _again_ :sweat_smile:

**Comment by Aran-Fey** [comment]
We use `mimetypes.guess_type` to determine the mime type based on the file extension. Could you tell us what the output of this code is on your machine?

```python
import mimetypes
print(mimetypes.guess_type('foo.js.gz'))
```

**Comment by mad-moo** [comment]
@Aran-Fey for the record, I've tried 3.10 & 3.12 (on Linux), and I get the expected result:

```py
>>> mimetypes.guess_type("foo.js.gz")
('text/javascript', 'gzip')
```

So I don't think it's the Python version. Bizarre

**Comment by dunivlorraine** [comment]
I tried to update to Python 3.13.0, but same result. Interestingly, we tried on another computer (same network), and it worked there.

**Comment by mad-moo** [comment]
Yep. As mentioned, I cannot reproduce this on any system, so clearly something is "special" about that one. Can you try this code again, but in a clean virtualenv? Maybe the Python installation just got screwed somehow.

```py
mimetypes.guess_type("foo.js.gz")
```

**Comment by mad-moo** [comment]
Okay some googling + the almighty ChatGPT suggest that Python is actually using the system's mimetype database. So it looks like your company screwed up the configuration somehow. @Aran-Fey considering how commonly Rio is used in organizations this will likely occur more often than we'd like. I'd suggest we move away from the `mimetypes` module where possible. What do you think?

**Comment by mad-moo** [comment]
I think that's also literally the only two types of files being served here. This is the function that serves Rio's internal frontend files iirc

**Comment by Aran-Fey** [comment]
According to my research, the expected mime type is actually `text/javascript`, not `application/javascript`. Just to be safe, can you confirm whether your browser accepts that?

**Comment by dunivlorraine** [comment]
Thanks for your feedback. Yes the `text/javascript` mime type works fine.
