### ISSUE TITLE
Disallow Submodules as `main-module` in `rio.toml`

### ISSUE THREAD

**Issue by mad-moo** [rio-labs/rio#156]
It is currently possible to specify submodules as the app's main module. For example, the `rio.App` can be located at `foo.bar` instead of `foo`. While this is convenient and _seems to_ sometimes work, it is not actually supported.

Rio relies on being able to determine the location of the file, by looking for a file/folder with that name in the project directory. Submodules don't adhere to this though - the Python code can run arbitrary operations, which makes it impossible to locate the correct files in general.

If we want to support this, all code should be reviewed and possibly some restrictions defined & documented. Until then, Rio should explicitly check to make sure the specified module is _not_ a submodule and notify the user.

**Comment by mad-moo** [comment]
@Aran-Fey I believe this is moot now?

**Comment by Aran-Fey** [comment]
It needs testing, but yeah
