### ISSUE TITLE
[BUG]: Broken Rendering in QT

### ISSUE THREAD

**Issue by mad-moo** [rio-labs/rio#166]
### Describe the bug

When using QT as the renderer for Rio (e.g. when using app mode on Linux), many of the HTML elements render incorrectly. Margins are missing, the MediaPlayer controls are in the wrong spot, bullet points appear wrong, just to name the things I've seen in the first 2 minutes.

### Steps to Reproduce

1. Create a Rio App
2. Set it to run in local app mode
3. Make sure `pywebview` uses the QT backend (install `pywebview[qt]` and uninstall any other libraries)

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/0955cf73-968b-4776-9642-5c89d1cf0e9f)
![image](https://github.com/user-attachments/assets/918e23af-d93b-4a69-a92b-a1e72635d3d7)

### Operating System

Linux

**Comment by iwr-redmond** [comment]
Make sure pyside6 is installed. It might need to be added to the dependency list. By default, pywebview still installs PyQT5 with WebKit.

Additionally, the GTK backend runs by default on Linux. Make sure gui='qt' is set [per the demo](https://pywebview.flowrl.com/examples/qt_test.html). This is not present in the code right now.

**Comment by mad-moo** [comment]
Don't worry. GTK is so obviously broken, I would notice if it was in use :)

I'll stick to the other thread just so everything is in one place.

**Comment by mad-moo** [comment]
Resolved by updating pywebview and forcing it to use pyside6.
