### ISSUE TITLE
please give a detailed help for rio command. 

### ISSUE THREAD

**Issue by gokulakkannan** [rio-labs/rio#167]
### Description

please give a detailed help for rio command. 

Fox example rio add don't have help.

### Suggested Solution

.

### Alternatives

.

### Additional Context

.

### Related Issues/Pull Requests

.

**Comment by mad-moo** [comment]
What exactly would you like us to add? There is already a help text for each subcommand

```bash
$ python -m rio help add
add  —  Add a page or component to the project

Usage: /home/jakob/Local/rio/rio/__main__.py add <what> <name>

  what  ...  Whether to add a `page` or a `component`
  name  ...  The name of the new page or component

The `add` command adds a new page or component to your project. A python file containing some template code will be created in the `pages` or `components` folder of your project.
```

The commands also ask you for any arguments that you don't pass in.

Would you be open to adding the changes you'd like to see and opening a PR? The code is in `rio/cli/__init__.py` (https://github.com/rio-labs/rio/blob/main/rio/cli/__init__.py)
