### ISSUE TITLE
[BUG]: Rio Website Side Bar Bug

### ISSUE THREAD

**Issue by mahmedalam** [rio-labs/rio#175]
### Rio Website Side Bar Bug

**Follow these steps to see this**

![Rio Sider Bar Bug 1](https://github.com/user-attachments/assets/180f5c58-e383-4326-ab06-46c96dee4bf1)
![Rio Sider Bar Bug 2](https://github.com/user-attachments/assets/fa0db59c-82a8-4985-a4d8-686828beb7cd)

### Fix this with css styles:

**For `rio-child-wrapper` class third container**
1. Add `max-height: 500px;`

**For `rio-card rio-component rio-switcheroo-neutral` classes child container**
1. Add `max-height: inherit;`
2. Add `overflow: auto;`

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome, Firefox, Edge

### What device are you using?

Desktop

**Comment by Aran-Fey** [comment]
This is already fixed, but we have yet to re-deploy the website with the bugfix. It should happen sometime within the next few days.
