### ISSUE TITLE
Bypass File Uploads when using `Session.pick_file`

### ISSUE THREAD

**Issue by iwr-redmond** [rio-labs/rio#178]
### Description

The app mode window (pywebview) requires additional configuration to allow uploads, similar to the code already present in [session.py's save_file function](https://github.com/rio-labs/rio/blob/main/rio/session.py#L2178).

### Suggested Solution

Implement the [webview.OPEN_DIALOG feature](https://pywebview.flowrl.com/examples/open_file_dialog.html) in [session.py's file_chooser function](https://github.com/rio-labs/rio/blob/main/rio/session.py#L2129). Optionally, you can integrate the [webview.dom.documents.events](https://pywebview.flowrl.com/examples/drag_drop.html) class for drag and drop support in app mode.

### Alternatives

Nil

**Comment by mad-moo** [comment]
Just to be clear, you aren't asking for a change in behavior, but want the file picker to bypass the file upload and use the file's path instead?

**Comment by iwr-redmond** [comment]
Yes, with the addition of a native file dialog that can be accessed by clicking on the drag and drop area (or, I suppose, a button if preferred when setting up the component) if Rio is running in app mode. See [Flet's demo](https://flet-controls-gallery.fly.dev/utility/filepicker) for something similar. Unlike Flet, which relies on third party components for its native file picker, pywebview uses Pyside/QT and would therefore be consistent across all desktop platforms.

I see that Drag and Drop has been added to the file picker code in the last few days, so adding the corresponding pywebview enabling code to make this work in app mode would also be helpful.
