### ISSUE TITLE
[BUG]: `rio.Table` column padding too wide since v0.7.5

### ISSUE THREAD

**Issue by joegilkes** [rio-labs/rio#30]
### Describe the bug

Following on from a conversation on Discord with @Aran-Fey yesterday, since v0.7.5 was released (which fixed `rio.Table` not resizing vertically when updated with new data) all `rio.Table`s now seem to use a much greater horizontal column padding to push the columns apart, sometimes to the edges of the browser window.

### Expected Behavior

When building a `rio.Table`, a sensible horizontal padding between table columns should be chosen to not spread the table over the entire width of its container, as was the case in v0.7.4.

### Steps to Reproduce

On Rio v0.7.4, create a project with the following `__init__.py`:

```python
from __future__ import annotations

from pathlib import Path
from typing import *  # type: ignore    s

import rio

class RootPage(rio.Component):
    def build(self) -> rio.Component:
        return rio.Column(
            rio.Table(
                {f'Col{i}': [i+1, i+2, i+3] for i in range(10)},
                show_row_numbers=False
            ),
            spacing=2,
            width=60,
            margin_bottom=4,
            align_x=0.5,
            align_y=0,
        )

app = rio.App(
    name='Table_MWE',
    pages=[
        rio.Page(
            name="Home",
            page_url='',
            build=RootPage,
        )
    ]
)
```

Use `rio run` to visualise the built site. The table will sensibly space out its columns, as in the first screenshot (rio_mwe_074)

Update Rio to v0.75 or newer (I'm now on v0.7.7) and visualise the site with `rio run`. The columns of the table will now be pushed apart as in the second screenshot (rio_mwe_077), resulting in a stretched table that becomes difficult to read with longer string values in its fields.

### Screenshots/Videos

![rio_mwe_074](https://github.com/rio-labs/rio/assets/53342420/137a6cfd-9b02-4695-9d1c-c0d3f5c7f48e)
![rio_mwe_077](https://github.com/rio-labs/rio/assets/53342420/abd9f1ec-fccb-4ce0-a841-216e8fca4453)

### Operating System

Linux

### What browsers are you seeing the problem on?

Chrome

### Browser version

124.0.6367.201

### What device are you using?

Desktop

**Comment by Aran-Fey** [comment]
Thanks for the bug report. It's fixed in 0.7.8.
