### ISSUE TITLE
Allow specifying additional files to watch

### ISSUE THREAD

**Issue by theVivern** [rio-labs/rio#49]
`rio run` automatically restarts the project when changes to Python files are detected. Some projects also depend on other files however, such as JSON or CSV data files. It would be nice for `rio run` to watch those as well.

There's a couple approaches to solving this:

1. Allow adding "negative" paths to `.rioignore.
2. Add command-line flags for this
3. Allow adding paths to `rio.toml`

**Comment by mahiro72** [comment]
Hello @theVivern , I'm interested in working on this issue. Would it be okay for me to pick it up?

**Comment by theVivern** [comment]
Hey @mahiro72 ! Really appreciate the offer. And yes, you absolutely can!

Let me know if you need help with anything.

**Comment by theVivern** [comment]
The recent pull request has implemented this feature, but after some discussion (both internally & on discord) I've decided to rework the app files a bit. I'll use this as opportunity to drop `.rioignore` alltogether and improve `rio.toml` instead.

**Comment by theVivern** [comment]
Fixed by 733d846d0181fdf40ea4cbfe58aedd1cd75adafe, and improved by subsequent commits

**Comment by mahiro72** [comment]
Thanks for the review! Sounds good, I appreciate your feedback.
