### ISSUE TITLE
Feature Request: Support Multiselect for `rio.Dropdown`

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#52]
### Discussed in https://github.com/rio-labs/rio/discussions/50

<div type='discussions-op-text'>

<sup>Originally posted by **Sn3llius** June  7, 2024</sup>
### Summary:
It would be great to have multiselect support for the rio.Dropdown component in Rio. This feature would enhance the usability and flexibility of dropdown menus by allowing users to select multiple options at once.

### Detailed Description:
Currently, the `rio.Dropdown` component supports single selection, which is sufficient for many use cases. However, there are scenarios where selecting multiple items from a dropdown is necessary. Adding multiselect functionality would greatly benefit users who need to choose several options without having to use multiple dropdown components or creating their own suboptimal solutions.

### Proposed Solution:
- Implement a multiselect mode for `rio.Dropdown` that can be activated through a new attribute (or potentially as a separate component).
- Ensure that selected items are displayed clearly within the dropdown, with an option to deselect each item.
- Provide keyboard and mouse support for selecting and deselecting multiple items.
- Allow for custom styling to accommodate different design requirements.
- Include support for components like checkboxes for selecting items

### Benefits:
- Improved user experience by reducing the need for multiple dropdowns.
- Increased flexibility in form design and data selection.
- Enhanced productivity for users needing to make bulk selections.

### Additional Context:

Multiselect dropdowns are common in many applications and frameworks, such as React and Flutter. Bringing this feature to Rio will align it with modern UI component standards and fulfill the needs of more complex user interactions.

**Looking forward to the discussion and feedback from the community!**</div>

**Comment by mad-moo** [comment]
This should be a new component, rather than being integrated into dropdowns IMHO. Multiselect would need a differetn API, and pass different event objects. This would be confusing for both the type checker & the user.

**Comment by mad-moo** [comment]
`rio.Popup` is about to learn a new position: `position="dropdown"`. This will allow users to build their own popup-like components by displaying arbitrary content with the same positioning logic as `rio.Dropdown`, thus taking care of this issue.
