### ISSUE TITLE
[BUG]: Fix Spurious Disconnects

### ISSUE THREAD

**Issue by theVivern** [rio-labs/rio#54]
### Describe the bug

After having Rio apps open for a while they will often quietly disconnect. There is no indication of this - connection lost popup doesn't show - but the app no longer responds to any user input.

### Expected Behavior

Either don't lose connection at all, or transparently re-establish one.

### Steps to Reproduce

- Open a Rio app
- Let it sit for a while
- Interact with it

### Operating System

Windows, Linux

### What browsers are you seeing the problem on?

Chrome, Firefox

### What device are you using?

Desktop, Mobile

**Comment by Aran-Fey** [comment]
This sounds similar to a bug I wrestled with when I refactored the `Transport` code. FastAPI websockets become unusable when the `_serve_websocket` function exits, but aren't closed. Maybe the websocket is entering its "unusable" state for some reason.
