### ISSUE TITLE
Improve Websocket Reconnect in Firefox

### ISSUE THREAD

**Issue by theVivern** [rio-labs/rio#58]
Firefox tracks websocket disconnection failures and once a certain threshold is exceeded throttles them. This leads to an annoying grey screen before further attempts are made. Improve on this:

- either test whether the server is running via HTTP requests (rather websockets)
- wait for longer between attempts (only in firefox?)

**Comment by Aran-Fey** [comment]
The frontend now uses HTTP requests (via `fetch`) to check if the server is online. Seems to have solved the problem, as far as I can tell.
