### ISSUE TITLE
 NumberInput Field with Decimals != 0 Changes Input When Numbers Are Entered "Slowly"

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#60]
### Describe the bug

When using a NumberInput field with decimals set to a value other than 0, the input behaves unexpectedly if numbers are entered slowly. Specifically, when decimals is set to 2, entering the number "20" results in "2.000" and then immediately changes to "2.00".

### Steps to Reproduce

1. Create a NumberInput field and set decimals to a value other than 0 (e.g., 2).
2. Begin entering a number, such as "20", into the field.
3. Enter the numbers at a "slow" pace.

### What browsers are you seeing the problem on?

Chrome, Edge

**Comment by theVivern** [comment]
I believe this has been fixed, correct?
