### ISSUE TITLE
Content of `TextInput` Not Scrollable on Safari

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#82]
### Describe the bug

The `TextInput` component is not scrollable when the content exceeds the visible area on Safari. This issue prevents users from being able to view or edit the full content.

### Expected Behavior
The `TextInput` should be scrollable, allowing users to view and edit all content.

### Actual Behavior
The `TextInput` is not scrollable, and the overflow content is not accessible.

### Steps to Reproduce

1. Open Safari.
2. Navigate to the page containing the `TextInput` component.
3. Enter content that exceeds the visible area of the `TextInput`.

### Operating System

MacOS

### What browsers are you seeing the problem on?

Safari

### What device are you using?

Desktop, Mobile

### Related Issues

#81 #83

**Comment by mad-moo** [comment]
I can't reproduce this in Epiphany. Since input fields are handled directly be each browser this is probably specific to Safari, and can't be reproduced with other webkit browsers.

**Comment by mad-moo** [comment]
As discussed in person, this is a non-issue.
