### ISSUE TITLE
`Dropdown` Settings for Component Examples Searchable but Not Selectable via Keyboard

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#84]
### Describe the bug

The `Dropdown` settings for component examples are searchable, but the search results cannot be selected using the keyboard. 

### Experienced Behavior
- The search result is found and displayed.
- The search result is **not** selectable using the keyboard.

### Expected Behavior
- The search result should be findable.
- The search result **should be** selectable using the keyboard. (e.g. pressing Enter or Tab)

### Steps to Reproduce

1. Navigate to a component example page with Dropdown settings.
2. Click into a search setting.
3. Search for any entry using the keyboard.

### Screenshots/Videos

<img width="277" alt="image" src="https://github.com/rio-labs/rio/assets/41641225/0af22aa4-e5f4-4b04-8c64-f5d61164d504">

### Operating System

Windows, MacOS

### What browsers are you seeing the problem on?

Chrome, Safari, Edge

### What device are you using?

Desktop, Mobile

**Comment by mad-moo** [comment]
Funny, I have the exact opposite issue. I can select, but not filter :smile:

**Comment by Sn3llius** [comment]
fixed
