### ISSUE TITLE
Image not displayed on Safari

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#85]
### Describe the bug

Images are not displaying correctly on Safari. This issue does not occur on other browsers like Chrome or Firefox.

### Steps to Reproduce

1. Open Safari.
2. Open image in docs.
3. Observe that the image is not displayed.

### Screenshots/Videos

<img width="554" alt="image" src="https://github.com/rio-labs/rio/assets/41641225/82debab0-b568-429a-8bcb-54ca3f7fefc6">

### Operating System

MacOS

### What browsers are you seeing the problem on?

Safari

### What device are you using?

Desktop, Mobile

**Comment by mad-moo** [comment]
I can't reproduce this. Can you verify this is still happening on the newest commit?
![image](https://github.com/rio-labs/rio/assets/24632992/4298cce1-dfb6-4ea2-a8e6-826df6efde2c)

If it does, we might have to test it in Safari proper, rather than just webkit

**Comment by Sn3llius** [comment]
Unfortunately, in the latest commit: 1a73abd6c1d00997c278f82bc10eee39b1619de9
