### ISSUE TITLE
`IconButton` are displayed with wrong size on Safari

### ISSUE THREAD

**Issue by Sn3llius** [rio-labs/rio#86]
### Describe the bug

`IconButtons` are not displayed correctly. They appear to have a to big size and are misaligned.

### Screenshots/Videos

<img width="380" alt="image" src="https://github.com/rio-labs/rio/assets/41641225/5d7e193c-abbe-4968-967b-8ad9c4a8f8c3">

**Comment by mad-moo** [comment]
I've made a change, and it seems to work in my browser now. Can you please re-test in safari?
