### ISSUE TITLE
[Feature Request] Remove Unused Dependencies

### ISSUE THREAD

**Issue by antipooh2** [rio-labs/rio#96]
### Description

When a package is installed, a chain of packages is installed **imy** -> **motor** -> **pymongo**. In this case, only **imy.docstrings** used

### Suggested Solution

Move imy.docstrings to project codebase (preserving copyright `Jakob Pinterits` in files)

**Comment by mad-moo** [comment]
Hey! 

Thanks for pointing this out. We definitely didn't mean to depend on a MongoDB driver.

The title makes it sound like there's more than one superfluous dependency. Did you find anything else?
